// cities were taken from https://overpass-turbo.eu/

export const cities_en = [
  'Adamantas',
  'Aegina',
  'Afantou',
  'Aghios Athanasios',
  'Agia Marina',
  'Agia Paraskevi',
  'Agia Varvara',
  'Agiasos',
  'Agios Dimitrios',
  'Agios Ioannis Rentis',
  'Agios Nikolaos',
  'Agios Pavlos',
  'Agrinio',
  'Aiginio',
  'Alexandreia',
  'Alexandroupoli',
  'Aliveri',
  'Almyros',
  'Amaliada',
  'Amarynthos',
  'Amfilochia',
  'Amfissa',
  'Ampelokipoi',
  'Anatoli',
  'Anatoliko',
  'Anavyssos',
  'Andravida',
  'Anemoessa',
  'Anthousa',
  'Antimachia',
  'Archaia Olympia',
  'Archanes',
  'Archangelos',
  'Argos Orestiko',
  'Argyroupoli',
  'Aridaia',
  'Arkalochori',
  'Arnea',
  'Arta',
  'Asprovalta',
  'Astakos',
  'Asvestochori',
  'Athina',
  'Chalandri',
  'Chalastra',
  'Chalkida',
  'Chalkidona',
  'Chania',
  'Cholargos',
  'Chora',
  'Dafni',
  'Deskati',
  'Diavata',
  'Dimini',
  'Drapetsona',
  'Eani',
  'Edessa',
  'Efkarpia',
  'Egaleo',
  'Elefsina',
  'Eleousa',
  'Elliniko',
  'Epanomi',
  'Eretria',
  'Ermoupoli',
  'Evropos',
  'Exochi',
  'Farsala',
  'Feres',
  'Filiates',
  'Filippiada',
  'Galatini',
  'Galatista',
  'Gastouni',
  'Giannitsa',
  'Glyfada',
  'Graikochori',
  'Grevena',
  'Gythio',
  'Hydra',
  'Ialysos',
  'Iasmos',
  'Ierápetra',
  'Igoumenitsa',
  'Ioannina',
  'Irakleia',
  'Iraklio',
  'Istiea',
  'Kainourgio',
  'Kalamaria',
  'Kalamata',
  'Kallithea',
  'Kalloni',
  'Kalyvia Thorikou',
  'Kamatero',
  'Kanallaki',
  'Kardamitsia',
  'Kardia',
  'Karitsa',
  'Karyes',
  'Kassandreia',
  'Kastoria',
  'Katerini',
  'Kato Achaea',
  'Kato Toumpa',
  'Katsikas',
  'Kavala',
  'Kefalos',
  'Keratea',
  'Kerkyra',
  'Kharilaou',
  'Kimmeria',
  'Kirinides',
  'Kolindros',
  'Konitsa',
  'Kopanos',
  'Korydallos',
  'Koufalia',
  'Kozani',
  'Krania',
  'Krestena',
  'Krya Vrysi',
  'Kymina',
  'Kyparissia',
  'Ladochori',
  'Lagyna',
  'Lamia',
  'Larissa',
  'Lavrion',
  'Lechena',
  'Lecheo',
  'Lefkada',
  'Leptokarya',
  'Limenaria',
  'Limenas Chersonisou',
  'Lindos',
  'Livadi',
  'Livanates',
  'Loutra Edipsou',
  'Makrakomi',
  'Mandra',
  'Maniaki',
  'Mantamados',
  'Marathonas',
  'Markopoulo',
  'Marousi',
  'Mataranga',
  'Medieval City of Rhodes',
  'Megali Panagia',
  'Megalopoli',
  'Megara',
  'Meliki',
  'Melissochori',
  'Menemeni',
  'Mesopotamia',
  'Messini',
  'Messolonghi',
  'Metsovo',
  'Moudros',
  'Naoussa',
  'Nea Artaki',
  'Nea Ionia',
  'Nea Kallikrateia',
  'Nea Magnisia',
  'Nea Malgara',
  'Nea Mesimvria',
  'Nea Michaniona',
  'Nea Moudania',
  'Nea Peramos',
  'Nea Selefkeia',
  'Nea Vrasna',
  'Neapoli',
  'Nemea',
  'Neo Petritsi',
  'Neochori',
  'Neochorouda',
  'Neoi Epivates',
  'Nikea',
  'Nikisiani',
  'Ntepo',
  'Néa Kíos',
  'Oraiokastro',
  'Ormilia',
  'Paiania',
  'Palaio Faliro',
  'Palea Fokea',
  'Paleochora',
  'Paloulia',
  'Panaitolio',
  'Panorama',
  'Pappados',
  'Paralía',
  'Paramythia',
  'Parga',
  'Parikia',
  'Patras',
  'Pefka',
  'Pefki',
  'Pella',
  'Penteli',
  'Peraia',
  'Perama',
  'Peristasi',
  'Peristeri',
  'Petroupolis',
  'Piraeus',
  'Plagiari',
  'Plaka',
  'Platamonas',
  'Platy',
  'Porto Spilia',
  'Preveza',
  'Ptolemaida',
  'Pylaia',
  'Pyrgos',
  'Roditsa',
  'Rodolivos',
  'Rodos',
  'Salamina',
  'Sapes',
  'Serres',
  'Servia',
  'Siatista',
  'Sidirokastro',
  'Simantra',
  'Sitia',
  'Skala',
  'Skaramangas',
  'Skoutari',
  'Sofades',
  'Stamata',
  'Stavros',
  'Tavros',
  'Thessaloniki',
  'Trikala',
  'Tsaritsani',
  'Tychero',
  'Varkiza',
  'Vartholomio',
  'Varympompi',
  'Vasilika',
  'Vasiliko',
  'Vathylakkos',
  'Vathý',
  'Velestino',
  'Velvendos',
  'Veroia',
  'Volos',
  'Vonitsa',
  'Vrondou',
  'Vyronas',
  'Zacharo',
  'Zagkliveri',
  'Zagora',
  'Zipari',
  'Zografou',
];
